### ISSUE TITLE
Failed to setup with Daikin thermostats + mini spliits

### ISSUE THREAD

**Issue by dph5087** [zlangbert/ha-daikinone#38]
I have 4 Daikin One Lite and 1 Daikin one touch thermostats connects to FTWRxxxxxxx indoor mini split units. When I added your integration, I received a "failed to setup" error. The logs show the following:

Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 9:53:38 PM (3 occurrences)
Last logged: 10:08:28 PM

Error setting up entry Daikin One for daikinone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinone/__init__.py", line 49, in async_setup_entry
    await data.update()
  File "/config/custom_components/daikinone/__init__.py", line 28, in update
    await self._update(no_throttle=no_throttle)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinone/__init__.py", line 37, in _update
    await self.daikin.update()
  File "/config/custom_components/daikinone/daikinone.py", line 201, in update
    await self.__refresh_thermostats()
  File "/config/custom_components/daikinone/daikinone.py", line 246, in __refresh_thermostats
    self.__thermostats = {device.id: self.__map_thermostat(device) for device in devices}
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinone/daikinone.py", line 278, in __map_thermostat
    equipment=self.__map_equipment(payload),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinone/daikinone.py", line 287, in __map_equipment
    if payload.data["ctAHUnitType"] < 255:
       ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'ctAHUnitType'

**Comment by clorteau** [comment]
Same here exactly. The Daikin ONE app reports the following equipment:
- 2x thermostat ONEPLUS software version 3.5.6
- indoor unit FDMQ24RVJU
- outdoor unit RX24RMVJU
- heat pump DZ17VSA361BA
- air handler DV36FECC14AB

**Comment by Zak707** [comment]
Found that after installing 2025.1.0 and updating addon to 0.8.0 (and later to 0.9.0) that new update to HA Core (i.e. 2025.1.1 & 2025.1.2) that after I had to do a reload or HVAC data would show unavailable. Settings\Devices & Service\Daikinone then once there click triple dot\Reload. (In fact you may see a 'failed to setup' message).

If that alone does not work, then restart HA after a core update and then do the above steps after everything is up.

Zak

**Comment by jstewar9** [comment]
Thanks for your response. I noticed that my version was 0.1.0 and the update status in HACS was "Unavailable". I ended up having to re-add the custom repository to HACS and manually downloading the newest version. Now it appears to be working for me.

**Comment by aaronaxvig** [comment]
Same issue here.  I have two One Touch thermostats and my dumped data doesn't contain any of the ctxxxxxUnitType keys.

**Comment by aaronaxvig** [comment]
I actually have the One+ Thermostat, sorry, for that inaccuracy.

**Comment by elads** [comment]
Hello! 
Like op, I get an error when attempting to add my equipment that includes the "KeyError: 'ctAHUnitType'"
I dont have the skills to attempt my own solutions, but happy to help test/buy coffee those who can. 
Dying to get this system integrated into HA.

I have the One Plus Smart Thermostat, software version 3.9.16, connected to a heat-pump mini-split: 
- Daikin FTX12NMVJU, 1 Ton Daikin AURORA Wall Mount
- Daikin RXL12WMVJU9, 1 Ton ccHP R32 HP

Full Error from HA log:
> Logger: homeassistant.config_entries
> Source: config_entries.py:762
> First occurred: February 2, 2026 at 17:48:49 (2 occurrences)
> Last logged: February 2, 2026 at 17:49:03
> Error setting up entry Daikin One for daikinone
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 762, in __async_setup_with_context
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/daikinone/__init__.py", line 49, in async_setup_entry
>     await data.update()
>   File "/config/custom_components/daikinone/__init__.py", line 28, in update
>     await self._update(no_throttle=no_throttle)  # type: ignore
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/daikinone/__init__.py", line 37, in _update
>     await self.daikin.update()
>   File "/config/custom_components/daikinone/daikinone.py", line 246, in update
>     await self.__refresh_thermostats()
>   File "/config/custom_components/daikinone/daikinone.py", line 307, in __refresh_thermostats
>     self.__thermostats = {device.id: self.__map_thermostat(device) for device in devices}
>                                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
>   File "/config/custom_components/daikinone/daikinone.py", line 345, in __map_thermostat
>     equipment=self.__map_equipment(payload),
>               ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
>   File "/config/custom_components/daikinone/daikinone.py", line 378, in __map_equipment
>     if payload.data["ctAHUnitType"] < 255:
>        ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
> KeyError: 'ctAHUnitType'


Thanks to posts above I found my way to the [mrworf](https://github.com/mrworf/ha-daikinone) edition. Trying that version, my system adds successfully, but it cannot show state from the system, and attempts to control it error out. Issues on that repo are closed.

UPDATE: for those in search of a solution. I next tried [apetrycki's daikinskyport](https://github.com/apetrycki/daikinskyport). and for my equiptment, this seems to be working!!!
